apiVersion: v1
kind: Service
metadata:
  name: fitnesstracker-api
  namespace: fitnesstracker
spec:
  selector:
    app: fitnesstracker-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
