apiVersion: v1
kind: Secret
metadata:
  name: fitnesstracker-secrets
  namespace: fitnesstracker
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "ChangeMe_123!"
  ConnectionStrings__DefaultConnection: "Server=fitnesstracker-db,1433;Database=FitnessTrackerDb;User Id=sa;Password=ChangeMe_123!;TrustServerCertificate=True;Encrypt=False;"
